name: Welcome New Contributors

on:
  pull_request_target:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login != github.repository_owner
    steps:
      - name: Welcome Message
        uses: actions/github-script@v7
        with:
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            const prNumber = context.payload.pull_request.number;
            const message = `👋 Hi @${prAuthor}, thanks for your first contribution! 🎉 We're happy to have you here.`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: message,
            });
